kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: pista-test
spec: 
  maxReplicas: 3
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: app/v1 
    kind: DeploymentConfig 
    name: pista-test 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 60